### ISSUE TITLE
Maven project depends on private repositories

### ISSUE THREAD

**Issue by silasdavis** [rarible/ethereum-indexer#30]
I have configured my maven `~/.m2/settings.xml` thusly (see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry):

```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">

    <activeProfiles>
        <activeProfile>rarible</activeProfile>
    </activeProfiles>

    <profiles>
        <profile>
            <id>rarible</id>
            <repositories>
                <repository>
                    <id>central</id>
                    <url>https://repo1.maven.org/maven2</url>
                </repository>
                <repository>
                    <id>rarible</id>
                    <url>https://maven.pkg.github.com/rarible/*</url>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
            </repositories>
        </profile>
    </profiles>

    <servers>
        <server>
            <id>rarible</id>
            <username>silasdavis</username>
            <password>REDACTED</password>
        </server>
    </servers>
</settings>
```

However I get various errors (maven complaining about/blocking non `http` in favour of `https`) but the the real issue is your parent POM depends on private Nexus repositories: https://github.com/rarible/parent-pom/blob/master/pom.xml#L19-L39

I note that this project was open sourced less than a month ago so its still early days. Is there any chance we could get a build that will work without access to private repos?

**Comment by silasdavis** [comment]
More broadly I think there might be some other dependency config I'm missing too, e.g. you seem to have a hard fork of https://github.com/daonomic/scala-rpc here: https://github.com/rarible/scala-rpc and the former package I could retrieve from bintray so wondering if that is being rewritten to the internal version of that package you are maintaining or something.

**Comment by johnrjj** [comment]
Just wanted to chime in -- I would love to contribute to this project and help it grow, but it's currently impossible to get up and running as an external contributor.

**Comment by sanufriev** [comment]
Hello, thank you very much your interest. Yes it is a great issue with  private nexus. Now we think what we should do to make it public

**Comment by alter** [comment]
@sanufriev hi, do you have any news about this issue?

**Comment by yakischik** [comment]
Current version in `master` branch could be built now, it is not using private repos anymore.
