### ISSUE TITLE
Support OpenSea's SeaPort orders

### ISSUE THREAD

**Issue by sunela** [rarible/ethereum-indexer#397]
When querying order data from the API, I only see Wyvern listings, that are currently being deprecated. I do not believe SeaPort orders are yet supported.

Example query;

`https://ethereum-api.rarible.org/v0.1/order/orders/sell/byItemAndByStatus?contract=0xbce3781ae7ca1a5e050bd9c4c77369867ebc307e&tokenId=4619`

for https://opensea.io/assets/ethereum/0xbce3781ae7ca1a5e050bd9c4c77369867ebc307e/4619

**Comment by sunela** [comment]
Awesome 🚀

**Comment by evgenynacu** [comment]
It's done now
